### ISSUE TITLE
爬取内容以及数据库结构设计

### ISSUE THREAD

**Issue by RicterZ** [Sharuru/Hgamecn-crawler#1]
游戏介绍：http://www.hgamecn.com/htmldata/articlelist/
获得信息包括Tag、开发商、发售日期以及游戏title。

Tag 对应游戏是多对多；
游戏对应开发商是一对多；

存在本地 sqlite 数据库就好。

:) 加油

**Comment by RicterZ** [comment]
另外，用BeautifulSoup吧

**Comment by RicterZ** [comment]
数据库有以下几个问题：
- game 和 publisher 是一对多的，但是数据库中这两个是完全独立，没有任何关联
- game 和 tag 是多对多，但是 game 中却有一个 tag 字段
- 关联表 games_tags 里面存放的最好是 game_id 和 tag_id，不要用 name，因为 name 已经在其各自字段存放了

大体就这么多，明天再改吧:P

**Comment by Sharuru** [comment]
吃我find大法

**Comment by RicterZ** [comment]
publisher 中的 publisher_game 这个字段不需要啦，game 中的 publisher 字段存放 publisher 的 id 就好
