### ISSUE TITLE
数据库多对多映射

### ISSUE THREAD

**Issue by Sharuru** [Sharuru/Hgamecn-crawler#3]

**Comment by Sharuru** [comment]
参考：
http://docs.sqlalchemy.org/en/rel_0_9/orm/tutorial.html#building-a-many-to-many-relationship
http://docs.sqlalchemy.org/en/rel_0_9/orm/relationships.html#many-to-many

**Comment by RicterZ** [comment]
该罚w

在 2014年8月14日，下午9:17，Mave Zhang notifications@github.com 写道：

**Comment by Sharuru** [comment]
罚啥（看了一下管理表的写法和那个不一样（然后表Class里还要单独写个relationship嗯（大概是这样？
另外，打个比方新入Tag时，做数据库遍历应该怎样？建个临时列表复制记录循环一下检测还是让Tag直接比对数据库记录比较好？（我猜数据库应该有直接的类似find的功能（前面看了一下，如果带写入的话，效率明显慢了（另外，find大法好！re辣鸡 QAQ

**Comment by Sharuru** [comment]
参考：
try:
    tag = session.query(Tag).filter(Tag.name=='xxx').one()
except xxxx:
    tag = Tag(name='xxx')
    session.add(Tag)
    session.commit()

**Comment by Sharuru** [comment]
参考：
publisher和game是 many to one
https://github.com/RicterZ/pyprint/blob/tornado/pyprint/models.py
