### ISSUE TITLE
数据库性能问题及其他细节问题

### ISSUE THREAD

**Issue by Sharuru** [Sharuru/Hgamecn-crawler#4]
- [x] 在本机运行一定时间后，数据库易锁死报错（大概是同步盘的问题）
  sqlalchemy.exc.OperationalError: (OperationalError) attempt to write a readonly database u'INSERT INTO publisher (name) VALUES (?)' (u'k-ten',)
- [x] 在VPS上运行，在ID51附近报0xe5编码错 【已转移至其他ISSUE】
- [x] linker函数的超时重连功能（error处理完全没有啊喂！ヽ(●-`Д´-)ノ 【坑】

**Comment by RicterZ** [comment]
大半夜更新issue也是醉了
数据库死锁问题我要 Google 一下到底是什么问题，我从没遇到过..

发自我的 iPad

**Comment by Sharuru** [comment]
一回家就开始忙东西，写了会代码没注意到是半夜，应该是我用坚果云备份的锁定文件问题（前面暂停掉跑了一下OK了，不过ID51附近的decode 错误不·可·避    (_ฅ́˘ฅ̀_)
详细错误信息：
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe5 in position 66: unexpected end of data
查了下0xe5

ID 52 Title：天使，请继续飞翔吧！
ID 51 Title：暗之，明之，淡之——《鬼作》于2004初夏
ID 50 Title：一切现实皆为虚幻，只有真爱永存——回忆《龙骑士4》
