### ISSUE TITLE
神奇的关联表保存数据问题

### ISSUE THREAD

**Issue by Sharuru** [Sharuru/Hgamecn-crawler#7]
完全不知道要怎么做 QAQ

**Comment by RicterZ** [comment]
唔ww
多看看例子，去 Google 搜一下w

发自我的 iPad

**Comment by Sharuru** [comment]
就是因为找不到才…

发自我的 iPhone

**Comment by Sharuru** [comment]
半夜刷微博的时候看到 @RicterZ 转发的一个Post: [SQLAlchemy多对多关系使用方法](http://blog.e3rp4y.me/2014/08/21/sqlalchemy-many-to-many-relationship.html)

尝试了一下, 确实很容易就能同时往'tags'以及'games_tags'里写入数据, 但是因为没有检测, 所以'tags'中会有多条重复记录, 如果加入检测的话, 复杂度又比原来的property方法高(说起来这就是property中setter要先清空list的原因?)

**Comment by RicterZ** [comment]
不是。
setter清空list的目的是为了重新给_tags赋值。
tags里没有重复的原因是那个find or create方法的功劳。

发自我的 iPad
